---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip
    - python3-venv
    - git

- name: Create application directory
  file:
    path: /opt/tempmon
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy Flask app
  copy:
    src: "/home/shobhakamlaskar/temp-mon3/app.py"
    dest: /opt/tempmon/app.py
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy templates
  copy:
    src: "/home/shobhakamlaskar/temp-mon3/templates/"
    dest: /opt/tempmon/templates
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create virtual environment
  command: python3 -m venv /opt/tempmon/venv
  args:
    creates: /opt/tempmon/venv

- name: Install Flask and psycopg2
  pip:
    name:
      - flask
      - python-dotenv
      - psycopg2-binary
    virtualenv: /opt/tempmon/venv
    virtualenv_command: python3 -m venv

- name: Copy .env
  copy:
    src: .env
    dest: /opt/tempmon/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create systemd service
  template:
    src: flaskapp.service.j2
    dest: /etc/systemd/system/flaskapp.service
    mode: '0644'
  notify: Restart flaskapp

- name: Enable and start flask service
  systemd:
    name: flaskapp
    state: started
    enabled: yes
    daemon_reload: yes
